### ISSUE TITLE
Unable to debug core dump

### ISSUE THREAD

**Issue by cyyzero** [osandov/drgn#382] opened 2024-01-30 06:03 UTC
Launching drgn gives the following error:

```
$ sudo drgn -c dump.202401250606 
drgn 0.0.23 (using Python 3.8.10, elfutils 0.189, with libkdumpfile)
Traceback (most recent call last):
  File "/usr/local/bin/drgn", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.8/dist-packages/drgn/cli.py", line 182, in _main
    prog.set_core_dump(args.core)
Exception: kdump_get_string_attr(KDUMP_ATTR_ARCH_NAME): Key has no value
```

machine environment:

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ cat /proc/version
Linux version 5.15.0-46-generic (buildd@lcy02-amd64-007) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022

$ drgn --version
drgn 0.0.23 (using Python 3.8.10, elfutils 0.189, with libkdumpfile)
```

BTW, drgn debugging live kernel works fine in this machine.

**Comment by brenns10** [comment] 2024-01-30 08:47
Hi @cyyzero, thanks for the report!

Drgn is trying to read information out of your core dump file and not finding it. In particular, it can't determine the CPU architecture for the core dump. This can sometimes happen when the program that produced the core dump wasn't able to get that information, or output the core dump slightly incorrectly. Could you share a bit more about how the core dump was generated? For example, was it generated after a panic & kexec using makedumpfile? Or from QEMU? Or some other source?

Some other information you could provide that might serve helpful is:

```
$ makedumpfile -v   # if it was generated by makedumpfile
$ file dump.202401250606
$ head -c 512 dump.202401250606 | xxd
```

If you're willing to build drgn from source, then you could try out a branch I've been working on, which could help work around or shed more light on the problem. You'd need to clone [this branch](https://github.com/brenns10/drgn/tree/vmcoreinfo):

```
$ git clone https://github.com/brenns10/drgn -b vmcoreinfo
$ cd drgn
```

Then follow the [instructions](https://github.com/osandov/drgn?tab=readme-ov-file#from-source) to build from source. With this branch, drgn has a couple new options:

```
  -a ARCH, --architecture ARCH
                        set the program architecture, in case it can't be
                        auto-detected
  -i VMCOREINFO, --vmcoreinfo VMCOREINFO
                        path to vmcoreinfo file (overrides any already
                        present in the file)
```

If, for example, you know that the core dump is from `x86_64`, you could specify that, so that drgn doesn't need to try to read that from the core dump:

```
drgn -c dump.202401250606 -a X86_64
```

It's possible that architecture isn't the only piece missing, so this might still fail - if it does, I can help with that too :)

Hopefully we can either shed light on what is producing core dumps missing data, or we can get a workaround, or both!

**Comment by cyyzero** [comment] 2024-01-31 08:47
@brenns10 Thank you for your reply! The source of this core dump is kdump, so it should be generated by the makedumpfile.

More detailed information is as follows: (Because of our company's security policy, I've hidden the hostname.)

```
$ makedumpfile -v
makedumpfile: version 1.6.7 (released on 16 Jan 2020)
lzo     enabled
snappy  disabled

$ sudo file dump.202401250606 
dump.202401250606: Kdump compressed dump v6, system x, node *******, release .0-46-generic, version 20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022, machine 64, domain e)

$ sudo head -c 512 dump.202401250606 | xxd 
00000000: 4b44 554d 5020 2020 0600 0000 7800 0000  KDUMP   ....x...
00000010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
(delete two lines of node name)
00000060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000080: 0000 0000 0000 0000 0000 352e 3135 2e30  ..........5.15.0
00000090: 2d34 362d 6765 6e65 7269 6300 0000 0000  -46-generic.....
000000a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000c0: 0000 0000 0000 0000 0000 0023 3439 7e32  ...........#49~2
000000d0: 302e 3034 2e31 2d55 6275 6e74 7520 534d  0.04.1-Ubuntu SM
000000e0: 5020 5468 7520 4175 6720 3420 3139 3a31  P Thu Aug 4 19:1
000000f0: 353a 3434 2055 5443 2032 3032 3200 0000  5:44 UTC 2022...
00000100: 0000 0000 0000 0000 0000 0000 7838 365f  ............x86_
00000110: 3634 0000 0000 0000 0000 0000 0000 0000  64..............
00000120: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000130: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000140: 0000 0000 0000 0000 0000 0000 0028 6e6f  .............(no
00000150: 6e65 2900 0000 0000 0000 0000 0000 0000  ne).............
00000160: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000170: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000180: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000190: 6014 0000 0000 0000 4bfa b165 0000 0000  `.......K..e....
000001a0: 0000 0000 0000 0000 0100 0000 0010 0000  ................
000001b0: 1800 0000 0064 0000 00ff ff18 0000 0000  .....d..........
000001c0: 0000 0000 0000 0000 0000 0000 0001 0000  ................
000001d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000001e0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000001f0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```

The output of the `file dump.202401250606` is a bit strange, it seems that subtracting 4 bytes of offset is the correct output.

Eventually, I am able to debug core dump properly with this branch you provided. Hopefully it will be merged into master soon!

**Comment by brenns10** [comment] 2024-01-31 16:53
Hi @cyyzero, with those details, I recognize this particular issue!

It's not with drgn, though I'm glad the workaround branch helped. We may merge parts of that at some point since it's helpful for these situations.

The issue is that in Linux kernel 5.11, torvalds/linux@9a56493f6942 ("uts: Use generic ns_common::count") was added, which removed 4 bytes from the `struct uts_namespace`, which makedumpfile uses to fill out the header of the core dump. As you saw, the system type (Linux) was shifted by 4 bytes which corrupted the core dump header.

The commit makedumpfile/makedumpfile@54aec38 ("[PATCH] make use of 'uts_namespace.name' offset in VMCOREINFO"), fixes the issue, but it is only present in makedumpfile 1.7.4, and your system has 1.6.7.

This is a consequence of using makedumpfile versions older than the kernel version you use. If your kernel is provided by your OS vendor, that's a bug on their behalf - they should be shipping compatible packages. If you installed this kernel via a PPA or some other source, then you're on your own for managing those sorts of things. You can check the output of `makedumpfile` and it will report whether or not it is compatible with a kernel as it attempts to dump it.  You can also check the README file of `makedumpfile` for any particular version, it contains a table of kernel compatibility.

**Comment by brenns10** [comment] 2024-02-01 17:24
If this resolves your issue, do you mind closing this? I don't actually have access to close issues on the Github repository :)

You can always reopen or file a new issue if necessary, we're glad to help.

Thanks!

**Closed** 2024-02-02 07:14 UTC
